/**
 * LISAN INTELLIGENCE — Share Utilities
 * 
 * PNG generation and Twitter intent for shareable signal cards.
 */

import { toPng } from 'html-to-image';
import { SignalOutput } from './engine/scoring';

// ============================================================================
// PNG GENERATION
// ============================================================================

/**
 * Generate a PNG from a DOM node
 */
export async function generatePng(node: HTMLElement): Promise<string> {
    try {
        const dataUrl = await toPng(node, {
            quality: 0.95,
            pixelRatio: 2, // High DPI for crisp images
            backgroundColor: '#0f172a', // Dark background
        });
        return dataUrl;
    } catch (error) {
        console.error('Failed to generate PNG:', error);
        throw error;
    }
}

/**
 * Download a data URL as a file
 */
export function downloadPng(dataUrl: string, filename: string): void {
    const link = document.createElement('a');
    link.download = filename;
    link.href = dataUrl;
    link.click();
}

// ============================================================================
// TWITTER INTENT
// ============================================================================

/**
 * Generate Twitter Web Intent URL
 */
export function getTwitterIntentUrl(signal: SignalOutput): string {
    const direction = signal.direction;
    const coin = signal.coin;
    const score = signal.score;
    const rrRatio = signal.riskRewardRatio.toFixed(1);

    const text = `📊 ${direction} $${coin} | Score: ${score}/100 | R:R ${rrRatio}:1

Generated by LISAN INTELLIGENCE
Free quantitative crypto signals.

🔗 lisanintel.com`;

    const encodedText = encodeURIComponent(text);
    return `https://twitter.com/intent/tweet?text=${encodedText}`;
}

/**
 * Open Twitter intent in new window
 */
export function openTwitterIntent(signal: SignalOutput): void {
    const url = getTwitterIntentUrl(signal);
    window.open(url, '_blank', 'width=600,height=400');
}

/**
 * Share signal to Twitter with PNG
 * Note: Twitter doesn't support direct image upload via intent,
 * so we download the image and open the intent separately
 */
export async function shareToTwitter(
    node: HTMLElement,
    signal: SignalOutput
): Promise<void> {
    try {
        // Generate and download PNG
        const dataUrl = await generatePng(node);
        const filename = `lisan_${signal.coin}_${signal.direction}_${Date.now()}.png`;
        downloadPng(dataUrl, filename);

        // Open Twitter intent
        openTwitterIntent(signal);
    } catch (error) {
        console.error('Failed to share to Twitter:', error);
        // Still open intent even if image generation fails
        openTwitterIntent(signal);
    }
}
